-- Importing Configurations
require('user.plugins')
require('user.nvim-tree-config')
require('user.bufferline-config')
require('user.keymappings')
require('user.opts')
require('user.term-config')
require('user.git-config')
require('user.indent-config')
require('user.dash-config')
require('user.cmp')
require('user.lsp')
require("user.colorschemes")
require("user.telescope")
require("user.treesitter")
